# Generated by Django 3.2.4 on 2021-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.BooleanField(default=False),
        ),
    ]
