# Generated by Django 3.2.4 on 2021-07-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_is_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='chat.message'),
        ),
    ]
