# Generated by Django 3.2.4 on 2021-07-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_audio_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioForMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio_messages/')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.audioformessage'),
        ),
    ]
